apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yhu5p0nf6-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yhu5p0nf6-python 
  name: yhu5p0nf6-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yhu5p0nf6-python 
